<?php

//  Call this function when data changes
function update_clients()
{
    mysql_query( "UPDATE pageGen SET id = id + 1 LIMIT 1" );
}

//  Call this function to get the ID to pass to JavaScript
function get_update()
{
    $result = mysql_query( "SELECT id FROM pageGen LIMIT 1" );
    $update = mysql_result( $result, 0, 'id' );
    return $update;
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="BookFace.png">
<title>BookFace</title>

<!-- Bootstrap -->
<link href="css/bootstrap.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	<style>
		
		.bg {
  background: url('back.jpg') no-repeat center center;
  position: fixed;
  width: 100%;
  height: 600px; /*same height as jumbotron */
  top:0;
  left:0;
  z-index: -1;
}

.jumbotron {
  height: 600px;
  color: white;
  text-shadow: #444 0 1px 1px;
  background:transparent;
}
		body{
			text-align: center;
		}
		

	</style>
	
	<script type="text/javascript">
	var pageGenID = 25218603  //  generated by PHP
	var processUpdate = function( response ) 
	{
	    if ( pageGenID < response ) 
	    {
	        replace_current_data_with_new_via_ajax();
	        pageGenID = response;
	    }
	}
	//  Compare our Page Generate ID against that of the server
	var checkUpdates = function()
	{
	    serverPoll = setInterval( function()
	    {
	        $.get('script_to_return_latest_pageGenID.php', 
	          { lastupdate: 1 }, 
	          processUpdate, 'html');
	    }, 10000 )
	};

	//  Check for updates every 10 seconds
	$( document ).ready( checkUpdates );

	</script>
</head>
<body style="padding-top: 70px">
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#topFixedNavbar1" aria-expanded="false"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
      <a class="navbar-brand" href="index.html" style="margin-top:-10px"><img src="BookFace.png" class="img-responsive" alt="Placeholder image"></a>
      <a class="navbar-brand" href="index.html">BookFace</a></div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="topFixedNavbar1">

      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://izdatwebsite.x10host.com">IzDatwebsite</a></li>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Chat Sites<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="http://izdatwebsite.x10host.com/chat/desk.php">Desktop Chat</a></li>
            <li><a href="http://izdatwebsite.x10host.com/chat/mobile.php">Mobile chat</a></li>
            <li><a href="#">Coming Soon</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="https://en.wikipedia.org/wiki/Adobe_Dreamweaver" target="_blank">Built With Dreamweaver</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="bg"></div>
<div class="jumbotron">
  <h1>&nbsp;</h1>
  <h1>Welcome to Bookface</h1>
<p class="lead">The Best Social Media Platform On The Planet</p>
</div>

<div class="container">
  <div class="row">
    <h2>Desktop Chat</h2>
    <h4>Last Updated on Nov 20</h4>
    <img src="desk.jpg" class="img-responsive" alt="Placeholder image">
    <br>
    <br>
    <br>
	  <a href="http://izdatwebsite.x10host.com/chat/desk.php" class="btn btn-primary button">Go to Desktop Chat</a>
	  
    
  </div>
  <hr>
  <div class="row">
  <h2>Mobile Chat</h2>
    <h4>Last Updated on Nov 20</h4>
    
    <img src="mobile.jpg"   alt="Placeholder image">
	  
    <br>
    <br>
    <br>
	  <a href="http://izdatwebsite.x10host.com/chat/mobile.php" class="btn btn-primary button">Go to Mobile Chat</a>
	  

  </div>
  <hr>
<div class="row">
   
    <h2>More Coming Soon!</h2>
    
	  

    
  </div>
 

<hr>

<div class="container">
	<div class="row">
      <div class="col-md-12 text-center"><p>Copyright &copy 2016 Colin Lin</p></div>
    </div>
</div>
	</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="js/jquery-1.11.3.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="/js/bootstrap.js"></script>
<script>
	var jumboHeight = $('.jumbotron').outerHeight();
function parallax(){
    var scrolled = $(window).scrollTop();
    $('.bg').css('height', (jumboHeight-scrolled) + 'px');
}

$(window).scroll(function(e){
    parallax();
});
</script>
	
</body>
</html>
